adapter: github
issue_tracker: github
meta-header: ""
table-pr:
    bug_fix: ['Bug Fix?', no]
    new_feature: ['New Feature?', no]
    bc_breaks: ['BC Breaks?', no]
    deprecations: ['Deprecations?', no]
    fixed_tickets: ['Fixed Tickets', '']
    license: ['License', MIT]
